name = "push-page-diff"
type = "webpack"
account_id = "7718b66fac7dfe0e5badaa986de51a5d"
workers_dev = true
route = "push"
webpack_config = "webpack.config.js"
# zone_id = ""
kv_namespaces = [ 
    { binding = "DIFF_KV", id = "ecdb66874bdd4b829dcafa56e67d43fc", preview_id = "2e703bb4411540d4a31793201788b09a" }
]

# TODO: for polling
# https://developers.cloudflare.com/workers/cli-wrangler/configuration#triggers
# Set up scheduled event listener https://developers.cloudflare.com/workers/runtime-apis/scheduled-event
# [triggers]
# crons = [""]

[site]
bucket = "./site"
entry-point = "."
